services:
  lnd:
    image: lightninglabs/lnd:v0.18.5-beta
    container_name: lnd
    restart: unless-stopped
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 2048M
        reservations:
          cpus: "1"
          memory: 100M
    volumes:
      - ./data/:/root/.lnd
      - ./lnd.conf:/root/.lnd/lnd.conf
      - ./scripts:/scripts
